@id_category=0d99578b-65a2-43e7-a470-544a1ab2740c

@id_recipe=52ae702e-7602-4c6e-a8db-b14a8cabbe28

### Get all categories
GET http://localhost:9080/food-blog/api/categories

### Get category by id
GET http://localhost:9080/food-blog/api/categories/{{id_category}}

### Create category
POST http://localhost:9080/food-blog/api/categories
Content-Type: application/json

{
  "name": "123",
  "type": "LUNCH"
}

### Update category
PUT http://localhost:9080/food-blog/api/categories/{{id_category}}
Content-Type: application/json

{
  "type": "BREAKFAST"
}

### Delete category
DELETE http://localhost:9080/food-blog/api/categories/{{id_category}}




### Get all recipes
GET http://localhost:9080/food-blog/api/recipes

### Get all recipes (by category)
GET http://localhost:9080/food-blog/api/categories/{{id_category}}/recipes

### Get specific recipe form specific category
GET http://localhost:9080/food-blog/api/categories/{{id_category}}/recipes/{{id_recipe}}

### Create recipe in category
POST http://localhost:9080/food-blog/api/categories/{{id_category}}/recipes
Content-Type: application/json

{
  "title": "test",
  "description": "created",
  "preparationTime": "1000"
}

### Update recipe
PUT http://localhost:9080/food-blog/api/categories/{{id_category}}/recipes/{{id_recipe}}
Content-Type: application/json

{
  "title": "test",
  "description": "updated",
  "preparationTime": "5000"
}

### Delete recipe
DELETE http://localhost:9080/food-blog/api/categories/{{id_category}}/recipes/{{id_recipe}}